"""Decidr Weekly Marketing Report — Streamlit viewer.

Embeds the self-contained HTML reports generated by generate.mjs (out/report-week-*.html).
Deploy on Streamlit Community Cloud from the GitHub repo.

IMPORTANT: this renders CONFIDENTIAL data. In Streamlit Cloud, restrict app viewers
to invited emails (Settings → Sharing) before sharing the URL.
"""
from pathlib import Path
import re

import streamlit as st
import streamlit.components.v1 as components

st.set_page_config(
    page_title="Decidr — Weekly Marketing Report",
    page_icon="📊",
    layout="wide",
)

OUT_DIR = Path(__file__).parent / "out"
reports = sorted(OUT_DIR.glob("report-week-*.html"))

if not reports:
    st.error(
        "No report found in `out/`. Generate one first:\n\n"
        "```\nnode generate.mjs --week 24\n```"
    )
    st.stop()

# Map "24" -> path, newest first.
def week_num(p: Path) -> int:
    m = re.search(r"week-(\d+)", p.stem)
    return int(m.group(1)) if m else 0

reports.sort(key=week_num, reverse=True)
labels = {f"Week {week_num(p)}": p for p in reports}

with st.sidebar:
    st.markdown("### Decidr weekly report")
    choice = st.selectbox("Reporting week", list(labels.keys()))
    st.caption("Confidential — for internal use. Restrict app viewers in Streamlit Cloud settings.")
    st.download_button(
        "⬇︎ Download HTML",
        data=labels[choice].read_text(encoding="utf-8"),
        file_name=labels[choice].name,
        mime="text/html",
    )

html = labels[choice].read_text(encoding="utf-8")
# The report is a long single page (~8 print pages); give the iframe room + internal scroll.
components.html(html, height=6200, scrolling=True)
